<?php
/**
 * blog/detail view file.
 *
 * @author     Satoshi Payne <satoshi.payne@gmail.com>
 * @copyright  Copyright (c) 2011 Satoshi Payne
 * @version    $Id: detail.phtml 105 2012-02-29 01:00:12Z Satoshi $
 * @category   Views
 * @package    Blog
 */
?>
<div class="containerArea clear">
<?php if($view->blog): ?>
	<h1><?= CHtml::encode($this->blogObj->getTitle()) ?></h1>
	<span class="date"><?= CHtml::encode($this->blogObj->getDateDisplay()->format('Y-m-d h:i:s')) ?></span>
	<span class="user"><?= CHtml::encode($this->blogObj->getAuthor()->getDisplayName()) ?></span>
	<div class="typography clear">
		<?= $this->blogObj->getContent() ?>
	</div>
	<hr />
	<div>
		<span>Comments (<?= $view->blog['commentCount'] ?>)</span>
	</div>
	
	<?php if($view->comments): ?>
		<ul>
		<?php foreach($view->comments as $i => $comment): ?>
			<li>
				<h3><?= CHtml::encode($comment->getTitle()) ?></h3>
				<span class="date"><?= CHtml::encode($comment->getDateCreated()->format('Y-m-d h:i:s')) ?></span>
				<span class="user"><?= CHtml::encode($comment->getAuthor()->getDisplayName()) ?></span>
				<p><?= nl2br(CHtml::encode($comment->getContent())) ?></p>
			</li>
		<?php endforeach ?>
		</ul>
		<div class="standardPaginationArea clear">
			<?= $view->pagination ?>
		</div>
		
		<?php if($view->canReply): ?>
			<form action="" method="post">
				<input type="hidden" name="FormAction" value="PostComment" />
				<input type="hidden" name="id" value="<?= $this->blogObj->getId() ?>" />
				
				<div>
					<label style="display: block;">Title</label>
					<input type="text" name="Title" value="" />
				</div>
				
				<div>
					<label style="display: block;">Comment</label>
					<textarea name="Comment" rows="6" cols="70"></textarea>
				</div>
				
				<input type="submit" value="Submit" />
			</form>
		<?php else: ?>
			<div>
				<p>You must be <a href="<?= $this->secureUrl ?>/login">logged in</a> to reply to this thread</p>
			</div>
		<?php endif ?>
	<?php endif ?>
<?php endif ?>
</div>