<?php
/**
 * blog/listing view file.
 *
 * @author     Satoshi Payne <satoshi.payne@gmail.com>
 * @copyright  Copyright (c) 2011 Satoshi Payne
 * @version    $Id: listing.phtml 105 2012-02-29 01:00:12Z Satoshi $
 * @category   Views
 * @package    Blog
 */
?>
<div class="containerArea clear">
	<div class="standardPaginationArea clear">
		<?= $view->pagination ?>
	</div>
	<?php if($view->blogs): ?>
		<ul>
		<?php foreach($view->blogs as $i => $blog): ?>
			<?php
			$blogObj = $blog['obj'];
			
			// Links.
			$linkPost       = CHtml::encode($this->siteUrl . $blogObj->getViewableLink());
			$linkPostAuthor = CHtml::encode($this->siteUrl . $blogObj->getAuthor()->getViewableLink());
			
			$link = CHtml::encode($this->siteUrl . $blogObj->getViewableLink());
			?>
			<li>
				<h3><a href="<?= $linkPost ?>"><?= CHtml::encode($blogObj->getTitle()) ?></a></h3>
				<span class="date"><?= CHtml::encode($blogObj->getDateDisplay()->format('Y-m-d h:i:s')) ?></span>
				<span class="user"><?= CHtml::encode($blogObj->getAuthor()->getDisplayName()) ?></span>
				<hr />
				<div>
					<a href="<?= $linkPost ?>">Read more</a> | <a href="<?= $link ?>#comments">Comments (<?= $blog['commentCount'] ?>)</a>
				</div>
				<?php if($blogObj->getTags()): ?>
					<div class="tags">
						<?php foreach($blogObj->getTags() as $i => $tag): ?>
						<?php
						$link = CHtml::encode($this->siteUrl . $tag->getViewableLink());
						?>
						<a href="<?= $link ?>"><?= CHtml::encode($tag->getTitle()) ?></a>, 
						<?php endforeach ?>
					</div>
				<?php else: ?>
					No tags
				<?php endif ?>
			</li>
		<?php endforeach ?>
		</ul>
	<?php endif ?>
	<?php // @incomplete ?>
	<div class="">
		Archives
	</div>
	<div class="">
		Categories
	</div>
	<div class="">
		Tags
	</div>
	<?php if($view->ads): ?>
		<?php foreach($view->ads as $i => $advert): ?>
			<?php
			$link = CHtml::encode($this->siteUrl . $advert->getViewableLink(array('request.hash' => $this->requestHash)));
			?>
			<br /><a href="<?= $link ?>"><?= CHtml::encode($advert->getTitle()) ?></a>
		<?php endforeach ?>
	<?php endif ?>
</div>